const GENERAL_CODE = {
  VALIDATION: "VALIDATION",
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
};

const AUTH_CODE = {
  USERNAME_EXIST: "USERNAME_EXIST",
  USER_EXIST: "USER_EXIST",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USERNAME_TAKEN: "USERNAME_TAKEN",
  USER_NOT_VERIFIED: "USER_NOT_VERIFIED",

  TOKEN_MISSING: "TOKEN_MISSING",
  INVALID_TOKEN: "INVALID_TOKEN",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",

  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  ALREADY_VERIFIED: "ALREADY_VERIFIED",
};

const OTP_CODE = {
  OTP_NOT_FOUND: "OTP_NOT_FOUND",
  INVALID_OTP: "INVALID_OTP",
};

const FOLLOW_CODE = {
  ALREADY_FOLLOWING: "ALREADY_FOLLOWING",
  NOT_FOLLOWING: "NOT_FOLLOWING",
  FOLLOWING_ID_MISSING: "FOLLOWING_ID_MISSING",
  CANNOT_FOLLOW_SELF: "CANNOT_FOLLOW_SELF",
  CANNOT_UNFOLLOW_SELF: "CANNOT_UNFOLLOW_SELF",
};

const VIDEO_CODE = {
  VIDEO_NOT_FOUND: "VIDEO_NOT_FOUND",
  VIDEO_ID_MISSING: "VIDEO_ID_MISSING",
};

const ERROR_CODE = {
  ...GENERAL_CODE,
  ...AUTH_CODE,
  ...OTP_CODE,
  ...FOLLOW_CODE,
  ...VIDEO_CODE,
};

export default ERROR_CODE;
