const GENERAL_CODE = {
  VALIDATION: "VALIDATION",
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  UNAUTHORIZED: "UNAUTHORIZED",
};

const AUTH_CODE = {
  USERNAME_EXIST: "USERNAME_EXIST",
  USER_EXIST: "USER_EXIST",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USERNAME_TAKEN: "USERNAME_TAKEN",
  USER_NOT_VERIFIED: "USER_NOT_VERIFIED",

  TOKEN_MISSING: "TOKEN_MISSING",
  INVALID_TOKEN: "INVALID_TOKEN",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",

  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  ALREADY_VERIFIED: "ALREADY_VERIFIED",
};

const OTP_CODE = {
  OTP_NOT_FOUND: "OTP_NOT_FOUND",
  INVALID_OTP: "INVALID_OTP",
};

const FOLLOW_CODE = {
  ALREADY_FOLLOWING: "ALREADY_FOLLOWING",
  NOT_FOLLOWING: "NOT_FOLLOWING",
  NO_FOLLOW_REQUEST: "NO_FOLLOW_REQUEST",
  FOLLOWING_ID_MISSING: "FOLLOWING_ID_MISSING",
  FOLLOWER_ID_MISSING: "FOLLOWER_ID_MISSING",
  CANNOT_FOLLOW_SELF: "CANNOT_FOLLOW_SELF",
  CANNOT_UNFOLLOW_SELF: "CANNOT_UNFOLLOW_SELF",
  INVALID_FOLLOW_REQUEST_STATE: "INVALID_FOLLOW_REQUEST_STATE",
};

const POST_CODE = {
  POST_NOT_FOUND: "POST_NOT_FOUND",
  POST_ID_MISSING: "POST_ID_MISSING",
};

const COMMENT_CODE = {
  COMMENT_NOT_FOUND: "COMMENT_NOT_FOUND",
};

const ERROR_CODE = {
  ...GENERAL_CODE,
  ...AUTH_CODE,
  ...OTP_CODE,
  ...FOLLOW_CODE,
  ...POST_CODE,
  ...COMMENT_CODE,
};

export default ERROR_CODE;
